// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhereIsMyVehicle.WebApi.Models;

namespace WhereIsMyVehicle.WebApi.Migrations
{
    [DbContext(typeof(WhereIsMyVehicleDbContext))]
    [Migration("20181129191136_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.GeoLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("GeoLocation");
                });

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LocationId");

                    b.Property<string>("Photo");

                    b.Property<int?>("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Sighting");
                });

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<string>("LicencePlate");

                    b.Property<int?>("LocationId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.Sighting", b =>
                {
                    b.HasOne("WhereIsMyVehicle.WebApi.Models.GeoLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("WhereIsMyVehicle.WebApi.Models.Vehicle", "Vehicle")
                        .WithMany("Sightings")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.Vehicle", b =>
                {
                    b.HasOne("WhereIsMyVehicle.WebApi.Models.GeoLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
