// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhereIsMyVehicle.WebApi.Data;

namespace WhereIsMyVehicle.WebApi.Migrations
{
    [DbContext(typeof(WhereIsMyVehicleDbContext))]
    partial class WhereIsMyVehicleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Photo");

                    b.Property<int?>("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Sightings");
                });

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<double>("LastKnownLatitude");

                    b.Property<double>("LastKnownLongitude");

                    b.Property<string>("LicensePlate");

                    b.Property<int>("Type");

                    b.Property<string>("UserEmail");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.Sighting", b =>
                {
                    b.HasOne("WhereIsMyVehicle.WebApi.Models.Vehicle", "Vehicle")
                        .WithMany("Sightings")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("WhereIsMyVehicle.WebApi.Models.Vehicle", b =>
                {
                    b.HasOne("WhereIsMyVehicle.WebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserEmail");
                });
#pragma warning restore 612, 618
        }
    }
}
